### ISSUE TITLE
Can we create an UI

### ISSUE THREAD

**Issue by mcagriaksoy** [damlaMtn/basic-chatbot#1]
Hello,

What do you think, I think we can create an UI to use bot with some configuration?

I have an idea also, for example, we can set some predefined configuration like behaving like a best friend, girlfriend and/or answer like psychologist etc etc.

**Comment by damlaMtn** [comment]
Hi,

This project is part of Coursera's IBM Full Stack Software Developer course. Since it is a full-stack project, it has a simple UI design. However, please feel free to improve and modify the project as you wish.
